# Generated by Django 2.2.4 on 2019-08-25 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_auto_20190818_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('short_name', models.CharField(max_length=5, null=True, verbose_name='短縮名')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
            options={
                'verbose_name': '役者',
                'verbose_name_plural': '役者',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('url', models.URLField(blank=True, verbose_name='リンク')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
            options={
                'verbose_name': '稽古場の施設',
                'verbose_name_plural': '稽古場の施設',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='部屋名')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Facility', verbose_name='施設')),
            ],
            options={
                'verbose_name': '稽古場',
                'verbose_name_plural': '稽古場',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='シーン名')),
                ('sortkey', models.IntegerField(default=0, verbose_name='ソートキー')),
                ('length', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='長さ')),
                ('length_auto', models.BooleanField(default=True, verbose_name='長さを自動で決める')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='完成度')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
            options={
                'verbose_name': 'シーン',
                'verbose_name_plural': 'シーン',
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始')),
                ('end_time', models.TimeField(verbose_name='終了')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehearsal.Place', verbose_name='稽古場')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
            options={
                'verbose_name': '稽古のコマ',
                'verbose_name_plural': '稽古のコマ',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('short_name', models.CharField(max_length=5, null=True, verbose_name='短縮名')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Actor', verbose_name='配役')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
            options={
                'verbose_name': '登場人物',
                'verbose_name_plural': '登場人物',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='From')),
                ('to_time', models.TimeField(verbose_name='To')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Actor', verbose_name='役者')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Rehearsal', verbose_name='稽古のコマ')),
            ],
            options={
                'verbose_name': '参加時間',
                'verbose_name_plural': '参加時間',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_num', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='セリフ数')),
                ('lines_auto', models.BooleanField(default=False, verbose_name='セリフ数を決めない')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Character', verbose_name='登場人物')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Scene', verbose_name='シーン')),
            ],
            options={
                'verbose_name': '出番',
                'verbose_name_plural': '出番',
            },
        ),
    ]
