# Generated by Django 2.2.4 on 2019-09-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, verbose_name='役名'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=50, verbose_name='施設名'),
        ),
        migrations.CreateModel(
            name='ScnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(verbose_name='作成日時')),
                ('modify_dt', models.DateTimeField(verbose_name='変更日時')),
                ('comment', models.TextField(verbose_name='メモ')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehearsal.Scene', verbose_name='シーン')),
            ],
            options={
                'verbose_name': 'シーンコメント',
                'verbose_name_plural': 'シーンコメント',
            },
        ),
    ]
