# Generated by Django 2.2.4 on 2019-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0002_auto_20190901_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scncomment',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='scncomment',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='scncomment',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='変更日時'),
        ),
    ]
