# Generated by Django 2.2.4 on 2019-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0003_auto_20190910_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='欠席'),
        ),
        migrations.AddField(
            model_name='scene',
            name='priority',
            field=models.IntegerField(choices=[(1, '最高'), (2, '高め'), (3, '普通'), (4, '低め'), (5, '最低')], default=3, verbose_name='優先度'),
        ),
    ]
