# Generated by Django 2.2.5 on 2019-09-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0004_auto_20190914_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sortkey',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='length_auto',
            field=models.BooleanField(default=True, verbose_name='長さは適当'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='sortkey',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
    ]
