# Generated by Django 2.2.5 on 2019-09-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0005_auto_20190915_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, verbose_name='短縮名'),
        ),
        migrations.AlterField(
            model_name='character',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehearsal.Actor', verbose_name='配役'),
        ),
        migrations.AlterField(
            model_name='character',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, verbose_name='短縮名'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehearsal.Place', verbose_name='稽古場'),
        ),
    ]
