# Generated by Django 2.2.5 on 2019-09-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20190818_2258'),
        ('rehearsal', '0006_auto_20190915_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='scncomment',
            name='mod_prod_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ProdUser', verbose_name='書いた人'),
        ),
    ]
