# Generated by Django 2.2.5 on 2019-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0008_auto_20191002_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='priority',
            field=models.IntegerField(choices=[(1, '最高'), (2, '高'), (3, '-'), (4, '低'), (5, '最低')], default=3, verbose_name='優先度'),
        ),
    ]
