# Generated by Django 2.2.5 on 2019-10-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0009_auto_20191002_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_allday',
            field=models.BooleanField(default=False, verbose_name='全日'),
        ),
    ]
