# Generated by Django 2.2.5 on 2019-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsal', '0010_attendance_is_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='to_time',
            field=models.TimeField(blank=True, null=True, verbose_name='To'),
        ),
    ]
