# Generated by Django 2.2.6 on 2019-11-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20190818_2258'),
        ('rehearsal', '0012_auto_20191026_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='prod_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ProdUser', verbose_name='アカウント'),
        ),
        migrations.CreateModel(
            name='AtndChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('old_value', models.CharField(max_length=50, verbose_name='変更前')),
                ('new_value', models.CharField(max_length=50, verbose_name='変更後')),
                ('changed_by', models.CharField(max_length=150, verbose_name='変更者')),
                ('changed_by_id', models.IntegerField(verbose_name='変更者ID')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='公演')),
            ],
        ),
    ]
