# Generated by Django 3.0.7 on 2020-06-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200607_0201'),
        ('rehearsal', '0014_auto_20191229_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='prod_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ProdUser', verbose_name='ユーザ'),
        ),
    ]
