# Generated by Django 3.0.7 on 2020-06-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200128_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['exp_dt'], 'verbose_name': '座組への招待', 'verbose_name_plural': '座組への招待'},
        ),
    ]
